### ISSUE TITLE
Benchmark Study Runs

### ISSUE THREAD

**Issue by msdogan** [msdogan/pyvin#20]
@jdherman we would like to perform multiple (so many) runs to compare solver and total run times for each solver we use. If we create 5 different data sets (different # of decision variables) for each solver (4 total) and 10 run for each to create error bars (originally 30), it makes 200 runs. Only changing thing in command in `batch` file would be `--solver` and `data.dat` paths.

```
pyomo solve --solver=cbc --solver-suffix=dual --solver-options="threads=32" pyvin.py $DIR/data.dat --json --report-timing --stream-solver
```

Is there a way to run `job script` recursively? Maybe a `for loop` in batch file :)

**Comment by msdogan** [comment]
@jdherman I have created benchmark run script and sent the job. It is one job file rather than multiple jobs. 1-year run (total 40 = 4 solvers X 10 trials) has just finished in 25 minutes, and now runnig 5-year dataset. I have created runs for 1-year, 5-year, 10-year, 40-year and 82-year. So, 5 datasets that makes 200 runs in total. I put a time limit of 400 hours but I think we are going to hit that especially with `glpk` solver. Anyway, if we hit the time limit bound, maybe I can create a separate job file only for `glpk`. I am not keeping `results.json`. I am only keeping track of time and objective function.

Here what the job file looks like:

```
#!/bin/bash
#SBATCH -D /home/msdogan/pyvin
#SBATCH -o /home/msdogan/pyvin/job.%j.%N.out
#SBATCH -e /home/msdogan/pyvin/job.%j.%N.err
#SBATCH -n 32            # Total number of processors to request (32 cores per node)
#SBATCH -p med           # Queue name hi/med/lo
#SBATCH -t 400:00:00        # Run time (hh:mm:ss) - 24 hours
#SBATCH --mail-user=msdogan@ucdavis.edu              # address for email notification
#SBATCH --mail-type=ALL                  # email at Begin and End of job

# you can define your own variables. Access them later with dollar signs ($DIR, etc.)
paths="benchmark/1-year benchmark/5-year benchmark/10-year benchmark/40-year benchmark/82-year"
# paths=benchmark/1-year
GDIR=/group/hermangrp
# solvers
solvers="cplex gurobi cbc glpk"
# number of trials
trials=$(seq 1 10)

# IMPORTANT: Python3/Pyomo/CBC solver are all installed in group directory. Add it to the path.
export PATH=$GDIR/miniconda3/bin:$GDIR/cbc/bin:$PATH

# Export CPLEX and GUROBI solvers
export CPLEX_HOME=$GDIR/cplex1263/cplex
export GUROBI_HOME=$GDIR/gurobi652/linux64
export PATH=$PATH:$GUROBI_HOME/bin:$CPLEX_HOME/bin/x86-64_linux:$GDIR/cbc/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GUROBI_HOME/lib:$CPLEX_HOME/lib/x86-64_linux/static_pic
export GRB_LICENSE_FILE=$GDIR/gurobi652/gurobi.lic

# if you want GLPK (serial)
# pyomo solve --solver=glpk --solver-suffix=dual pyvin.py $DIR/data.dat --json --report-timing --stream-solver

# if you want CBC (parallel, can only use up to 32 cores)
# if you want to use CPLEX or GUROBI solvers, change "--solver=cbc" to "--solver=cplex" or "--solver=gurobi"
# if you want to define number of cores use "--solver-options="threads=32""
for path in $paths
do
	for solver in $solvers
	do
		for trial in $trials
		do
			pyomo solve --solver=$solver --solver-suffix=dual pyvin.py $path/data.dat --json --report-timing > $path/$solver/output_trial_$trial.txt --stream-solver
		done
	done
done
# the --stream-solver flag gives verbose output if you want to see what's going on. If you don't care about this, remove it.

# At this point the results.json file should exist. Now we can postprocess. (This does not run in parallel; you could do it separately after the job finishes)

# mv results.json $DIR && cd $DIR
```

**Comment by jdherman** [comment]
@msdogan awesome!! Couple of thoughts:

* You might have to make sure all of the `$path/$solver` folders exist before it tries to save those files. You could `mkdir $path/$solver` inside the loop before running `pyomo solve`

* Does `results.json` just get overwritten every time a new solver runs? If so that's fine, I agree we don't care about it. But if it's saving copies that are ~1 GB each you might just want to `rm results.json` after every call to `pyomo solve`.

Let's see what these things can do!

**Comment by msdogan** [comment]
@jdherman benchmark runs are in debug mode because any time period less than 82-year results in infeasibility without debug mode. Would that be a problem for benchmark runs? It will take a bit longer to run those because there is more decision variables.

Status update:
* 1, 5, 10-year runs are done for all solvers
* 40-year run is done for cplex, gurobi and cbc. Glpk is still running
* 82-year, only cplex finished 8 runs out of 10.

**Comment by jdherman** [comment]
It's fine to run them in debug mode, as long as we report the true number of decision variables, including debug links. For the benchmark timings we're less interested in the actual flows in the system anyway.

Sounds good! Run them for as long as you need to run them. Let me know if I can help write a scraper for the results files.

Thanks again for running the shortcourse on Friday, it gave me some ideas for how we could revise this code in the future ... but not right now, it's working fine :)

**Comment by msdogan** [comment]
@jdherman I am excited to share benchmark results. Based on results, new champion is `gurobi`.
I created a new branch for benchmark runs but if you think that it should be in master branch, I can create a pull request. I plotted two results: solver reported time (or solver runtime), and pyomo finished (total PyVIN runtime). All results are coming from text files and `benchmark.py` retrieves them, summarizes outputs (https://github.com/msdogan/pyvin/blob/benchmark/benchmark/output.csv) and creates plots. I also created some statistics, such as mean, median and standard deviation because there is some outliars.

**Following figure shows solver reported times for each run size (# of decision variables:**
[solver reported time](https://github.com/msdogan/pyvin/blob/benchmark/benchmark/solver_8.pdf)

stats:
[solver reported time](https://github.com/msdogan/pyvin/blob/benchmark/benchmark/stats_solver%20reported%20time%20(s).csv)

**Total model runtime depending on number of decision variables with trendlines and equations:**
[total model runtime](https://github.com/msdogan/pyvin/blob/benchmark/benchmark/variable_6.pdf)

stats:
[total runtime](https://github.com/msdogan/pyvin/blob/benchmark/benchmark/stats_pyomo%20finished%20(sec).csv)

**Comment by jdherman** [comment]
Hi Mustafa, this is great to have multiple trials. I guess our CPLEX result from last time was just a lucky trial. So we can trust this result more.

I agree we can keep a separate branch for these results. Let's focus on the solver time only (not the total time), because the output file writing operations could be affected by other things happening on the filesystem at the same time. 

@mfefer want to use these updated solver results for your EWRI poster? :)
