### ISSUE TITLE
Deciding precision of parameters in matrix export

### ISSUE THREAD

**Issue by msdogan** [msdogan/pyvin#30]
This is a minor enhancement but @jrmerz asked in our last chat about what precision we want for each parameter (cost, amplitude, lower bound, upper bound) in matrix export. Some numbers are ridiculously long.

```
SR_SHA.2002-10-31	SR_SHA.2002-11-30	1	-2.973775927491251	0.9974443500372581	737.3889770000001	737.3889770000001
```

**Comment by jrmerz** [comment]
sure, perhaps a new issue in calvin-network-tools so the feature can be tracked?  Also, will need a more precise number than 2-3 and 5-6 :)

**Comment by msdogan** [comment]
alright moving this issue to calvin-network-tools
