### ISSUE TITLE
Checking bounds and costs with random samples

### ISSUE THREAD

**Issue by msdogan** [msdogan/pyvin#35]
I randomly picked links for all possible bound and cost cases I can think of from the database. I am going to check those cases only to see if there is any problem since it is hard to check all of them one-by-one. If everything looks good but we still get some considerable flow differences, then we can focus on that problematic links.

Here are random links for each bound and cost cases:

```
Bound Examples
	Lower bound only
		Constant:	D511-D55
		Monthly Varying:	C120-SR_OL
		Time-series:	D507-D509, D675-D676
	Upper Bound only
		Constant:	C49-C51, C62-N10
		Monthly Varying:	C75-D845
		Time-series:	HU206-CVPM09S, HXI210-Ext_Stockton
	Lower Bound & Upper Bound (not fixed)
		Constant:	SR_GNT-SR_GNT, SR_BER-SR_BER
		Monthly Varying: SR_BUL-SR_BUL
		Time-series:	SR_SHA-SR_SHA, SR_CLE-SR_CLE, SR_FOL-SR_FOL
	Constrained (fixed)
		Constant:	Do not exist
		Monthly Varying:	Do not exist
		Time-series:	D541-Required_Delta_Outflow, C20-D55

Cost Examples
	Constant
		Unit Cost:	HGP21-A409A
	Piecewise Curve
		Negative Slope:	C23-C25, HU203_CVPM06G
		Positive Slope:	PMP_OSO-D884
```

**Comment by msdogan** [comment]
Bound examples
- [ ] D511-D55
- [ ] C120-SR_OL
- [ ] D507-D509, D675-D676
- [ ] C49-C51, C62-N10
- [ ] C75-D845
- [ ] HU206-CVPM09S, HXI210-Ext_Stockton
- [ ] SR_GNT-SR_GNT, SR_BER-SR_BER
- [ ] SR_BUL-SR_BUL
- [ ] SR_SHA-SR_SHA, SR_CLE-SR_CLE, SR_FOL-SR_FOL
- [ ] D541-Required_Delta_Outflow, C20-D55

Cost Examples
- [ ] HGP21-A409A
- [ ] C23-C25, HU203_CVPM06G
- [ ] PMP_OSO-D884

**Comment by msdogan** [comment]
All randomly picked bound and cost examples are compared to CALVIN (run S09I05), and there is no problem. Closing the issue.

**Comment by jdherman** [comment]
Thanks! Good use of the monte carlo technique :)
